---
title: "clean data"
output: html_notebook
---

```{r}
library(tidyverse)
library(readxl)
library(fs)
```

https://github.com/libjohn/openrefine/blob/master/data/salary.xlsx

```{r}
my_data_url <- "https://github.com/libjohn/openrefine/raw/master/data/salary.xlsx"

if (!fs::file_exists("data/excel/my_excel_file.xlsx")) {
  fs::dir_create("data/excel")
  curl::curl_download(my_data_url, "data/excel/my_excel_file.xlsx", mode = "wb")
}

my_df <- read_xlsx("data/excel/my_excel_file.xlsx", 
                    sheet = "2013-2014",
                    col_names = FALSE)

# this file is deleted in the last code chunk of ths script.
```


```{r}
my_df %>% 
  rename(player = 1, "salary" = 2, "notes" = 3) 
```

```{r}
my_df %>% 
  rename(player = 1, "salary" = 2, "notes" = 3) %>% 
  filter(player != "----")
```

```{r}
cleaned_df <- my_df %>% 
  rename(player = 1, salary = 2, notes = 3) %>% 
  filter(player != "----") %>% 
  mutate(notes = if_else(player == "Cleveland Cavaliers", salary, notes)) %>% 
  mutate(salary = if_else(salary == "Tot $66,611,520", NA_character_, salary)) %>% 
  mutate(team = if_else(is.na(salary), player, NA_character_)) %>% 
  fill(team) %>% 
  filter(!is.na(salary)) %>% 
  mutate(salary = as.numeric(salary))
cleaned_df
```

```{r}
cleaned_df %>% 
  group_by(team) %>% 
  summarise(total_salary = sum(salary), median_salary = median(salary), 
            mean_salary = mean(salary), min_salary = min(salary),
            max_salary = max(salary))
```

```{r fig.height=9, fig.width=12}
cleaned_df %>% 
  group_by(team) %>% 
  summarise(total_salary = sum(salary), median_salary = median(salary), 
            mean_salary = mean(salary), min_salary = min(salary),
            max_salary = max(salary)) %>%
  pivot_longer(total_salary:max_salary, names_to = "salary_type") %>% 
  ggplot(aes(fct_reorder(team, value), value)) +
  geom_col() +
  coord_flip() +
  facet_wrap(~ salary_type, scales = "free_x") +
  scale_y_continuous(labels = scales::comma)
```

```{r}
my_plots <- function(my_df) {
   ggplot(data = {{my_df}}, 
          aes(y = fct_reorder(team, value), x = value)) + 
    geom_col() + 
    scale_x_continuous(labels = scales::label_dollar(scale_cut = scales::cut_short_scale()
                                                     ))
}
```


```
{r}
cleaned_df %>% 
  group_by(team) %>% 
  summarise(total_salary = sum(salary), median_salary = median(salary), 
            mean_salary = mean(salary), min_salary = min(salary),
            max_salary = max(salary)) %>%
  pivot_longer(total_salary:max_salary, names_to = "salary_type") %>% 
  group_by(salary_type) %>%
  nest(data = -salary_type) %>%
  mutate(my_plot = map(data, ~ ggplot(data = .x, aes(y = fct_reorder(team, value), x = value)) + geom_col() + scale_x_continuous(labels = scales::label_dollar(
    scale_cut = scales::cut_short_scale()
  ))
))   %>%
  mutate(myplot_wtitle = map(my_plot, ~ .x + ggtitle(salary_type))) %>%
  pull(myplot_wtitle)
```


```{r}
cleaned_df %>% 
  group_by(team) %>% 
  summarise(total_salary = sum(salary), median_salary = median(salary), 
            mean_salary = mean(salary), min_salary = min(salary),
            max_salary = max(salary)) %>%
  pivot_longer(total_salary:max_salary, names_to = "salary_type") %>% 
  group_by(salary_type) %>%
  nest(data = -salary_type) %>%
  mutate(my_plot = map(data, my_plots))   %>%
  mutate(myplot_wtitle = map(my_plot, ~ .x + ggtitle(salary_type))) %>%
  pull(myplot_wtitle) 
```

```{r}
fs::dir_delete("data/excel")
```

