---
title: "clean data"
output: html_notebook
---

```{r}
library(tidyverse)
library(readxl)
library(fs)
```

[Household Pulse Survey Data Tables]("https://www.census.gov/programs-surveys/household-pulse-survey/data.html") >   
[Week 1 Household Pulse Survey: April 23 - May 5]("https://www.census.gov/data/tables/2020/demo/hhp/hhp1.html") > Housing Tables > [Table 2b. Confidence in Ability to Make Next Month's Payment for Renter Occupied Housing]("https://www2.census.gov/programs-surveys/demo/tables/hhp/2020/wk1/housing2b_week1.xlsx")
  

```{r}
my_data_url <- "https://www2.census.gov/programs-surveys/demo/tables/hhp/2020/wk1/housing2b_week1.xlsx"

if (!fs::file_exists("data/excel/housing2b_week1.xlsx")) {
  fs::dir_create("data/excel")
  curl::curl_download(my_data_url, "data/excel/housing2b_week1.xlsx", mode = "wb")
}

my_df <- read_xlsx("data/excel/housing2b_week1.xlsx", 
                   sheet = "NC",
                   skip = 3)
                   # col_types = c("text", rep("numeric", 9)))

my_df_varnames <- read_xlsx("data/excel/housing2b_week1.xlsx", 
                            sheet = "NC",
                            skip = 4)

chart_metadata <- read_xlsx("data/excel/housing2b_week1.xlsx", 
                            sheet = "NC",
                            n_max = 3,
                            col_names = FALSE) %>% 
  pull(1)
chart_title <- chart_metadata[1]
chart_source <- chart_metadata[2]
chart_subtitle <- chart_metadata[3]

my_df <- my_df %>%
  janitor::clean_names()


glimpse(my_df)

names(my_df_varnames)[4:9]
names(my_df)[4:9] <- names(my_df_varnames)[4:9]  
names(my_df)
# this file is deleted in the last code chunk of this script.
```


```{r}
my_levels <- rev(c("No confidence",	"Slight confidence", "Moderate confidence", 
               "High confidence", "Payment is/will be deferred", "Did not report"))

my_educ_levels <- c("Less than high school", "High school or GED", 
                    "Some college/associate’s degree", "Bachelor’s degree or higher")

my_df %>% 
  filter(select_characteristics != "Total") %>% 
  mutate(sub_group = if_else(is.na(total), select_characteristics, NA_character_)) %>% 
  fill(sub_group, .direction = "down") %>% 
  relocate(sub_group) %>% 
  drop_na(total) %>% 
  filter(sub_group == "Education") %>% 
  mutate(across(total:last_col(), ~ as.numeric(.x))) %>% 
  pivot_longer(`No confidence`:`Did not report`, names_to = "my_category") %>%
  group_by(sub_group, select_characteristics, my_category) %>% 
  summarise(totals = sum(value, na.rm = TRUE)) %>% 
  mutate(my_category = fct_relevel(my_category, my_levels)) %>%
  ggplot(aes(totals, my_category)) +
  geom_col() +
  scale_x_continuous(labels = scales::label_dollar(scale_cut = scales::cut_short_scale())) +  
  facet_wrap(~ fct_relevel(select_characteristics, my_educ_levels)) +
  theme(plot.title.position = "plot") +
  labs(title = str_wrap(chart_title, 80), subtitle = str_glue("NC ", chart_subtitle),
       caption = chart_source, x = "", y = "")
```

```{r}
my_df %>% 
  rename(player = 1, "salary" = 2, "notes" = 3) %>% 
  filter(player != "----")
```

```{r}
cleaned_df <- my_df %>% 
  rename(player = 1, salary = 2, notes = 3) %>% 
  filter(player != "----") %>% 
  mutate(notes = if_else(player == "Cleveland Cavaliers", salary, notes)) %>% 
  mutate(salary = if_else(salary == "Tot $66,611,520", NA_character_, salary)) %>% 
  mutate(team = if_else(is.na(salary), player, NA_character_)) %>% 
  fill(team) %>% 
  filter(!is.na(salary)) %>% 
  mutate(salary = as.numeric(salary))
cleaned_df
```

```{r}
cleaned_df %>% 
  group_by(team) %>% 
  summarise(total_salary = sum(salary), median_salary = median(salary), 
            mean_salary = mean(salary), min_salary = min(salary),
            max_salary = max(salary))
```

```{r fig.height=9, fig.width=12}
cleaned_df %>% 
  group_by(team) %>% 
  summarise(total_salary = sum(salary), median_salary = median(salary), 
            mean_salary = mean(salary), min_salary = min(salary),
            max_salary = max(salary)) %>%
  pivot_longer(total_salary:max_salary, names_to = "salary_type") %>% 
  ggplot(aes(fct_reorder(team, value), value)) +
  geom_col() +
  coord_flip() +
  facet_wrap(~ salary_type, scales = "free_x") +
  scale_y_continuous(labels = scales::comma)
```

```{r}
my_plots <- function(my_df) {
   ggplot(data = {{my_df}}, 
          aes(y = fct_reorder(team, value), x = value)) + 
    geom_col() + 
    scale_x_continuous(labels = scales::label_dollar(scale_cut = scales::cut_short_scale()
                                                     ))
}
```


```
{r}
cleaned_df %>% 
  group_by(team) %>% 
  summarise(total_salary = sum(salary), median_salary = median(salary), 
            mean_salary = mean(salary), min_salary = min(salary),
            max_salary = max(salary)) %>%
  pivot_longer(total_salary:max_salary, names_to = "salary_type") %>% 
  group_by(salary_type) %>%
  nest(data = -salary_type) %>%
  mutate(my_plot = map(data, ~ ggplot(data = .x, aes(y = fct_reorder(team, value), x = value)) + geom_col() + scale_x_continuous(labels = scales::label_dollar(
    scale_cut = scales::cut_short_scale()
  ))
))   %>%
  mutate(myplot_wtitle = map(my_plot, ~ .x + ggtitle(salary_type))) %>%
  pull(myplot_wtitle)
```


```{r}
cleaned_df %>% 
  group_by(team) %>% 
  summarise(total_salary = sum(salary), median_salary = median(salary), 
            mean_salary = mean(salary), min_salary = min(salary),
            max_salary = max(salary)) %>%
  pivot_longer(total_salary:max_salary, names_to = "salary_type") %>% 
  group_by(salary_type) %>%
  nest(data = -salary_type) %>%
  mutate(my_plot = map(data, my_plots))   %>%
  mutate(myplot_wtitle = map(my_plot, ~ .x + ggtitle(salary_type))) %>%
  pull(myplot_wtitle) 
```

```{r}
fs::dir_delete("data/excel")
```

