---
title: "iterte with Excel files"
output: html_notebook
---

```{r}
library(tidyverse)
library(readxl)
library(fs)
library(rvest)
```

census pulse survey
https://www.census.gov/newsroom/press-kits/2020/pulse-surveys.html

census pulse surveys household experience data
https://www.census.gov/data/experimental-data-products/household-pulse-survey.html

Summary Navigation page:
https://www.census.gov/programs-surveys/household-pulse-survey/data.html

weekly pulse surveys
https://www.census.gov/data/tables/2020/demo/hhp/hhp13.html

Example week 13 housing pulse survey file 2b
https://www2.census.gov/programs-surveys/demo/tables/hhp/2020/wk7/housing2b_se_week7.xlsx
https://www2.census.gov/programs-surveys/demo/tables/hhp/2020/wk13/housing2b_se_week13.xlsx
https://www2.census.gov/programs-surveys/demo/tables/hhp/2021/wk37/housing2b_week37.xlsx
https://www2.census.gov/programs-surveys/demo/tables/hhp/2022/wk45/housing2b_week45.xlsx

```{r}
wk_number <- 1:52
wk_number
```

```{r}
my_url <- "https://www.census.gov/programs-surveys/household-pulse-survey/data.html"
base_url <- "https://www.census.gov/"

my_results <- read_html(my_url)
```


```{r}

link_text_1 <- my_results %>% 
  html_nodes(".uscb-title-3") %>% # .uscb-title-3
  html_text2()
link_text_1

link_text2 <- my_results %>% 
  html_nodes("a.uscb-list-item") %>% # .uscb-title-3
  html_text2()
link_text2

link_url <- my_results %>% 
  html_nodes("a.uscb-list-item") %>% 
  html_attr("href")
link_url
  

my_crawl <- tibble(link_text_1, link_url, base_url, link_text2) %>% 
  filter(str_detect(link_text_1, "Household Pulse Survey:")) %>% 
  mutate(link_text2 = str_replace_all(link_text2, "\\n", "|")) %>% 
  mutate(full_url = str_c(base_url, link_url)) %>% 
  mutate(full_url = str_replace(full_url, 'gov//data', 'gov/data')) %>% 
  relocate(full_url)
my_crawl


  
  # html_nodes("#setwidth li a") %>% 
  # html_text()  
```

```{r}
next_url <- "https://www.census.gov/data/tables/2021/demo/hhp/hhp37.html"
```

```{r}

deep_pages <- read_html(next_url)

dp_links <- deep_pages %>% 
  html_nodes("a") %>% 
  html_attr("href")
dp_links

dp_link_2b <- tibble(dp_links) %>% #, dp_link_text) %>% 
  filter(str_detect(dp_links, "housing2b")) 
dp_link_2b
```

```{r}
my_crawl %>%
  tail(3)  %>% 
  select(link_text_1, full_url) %>% 
  nest(data = -link_text_1)     %>% 
  mutate(deep_page = map(data, read_html, full_url))  
  select(full_url, deep_page) %>%

  mutate(dp_links = map(deep_page, ~ .x %>% 
                          html_nodes("a") %>% 
                          html_attr("href") ))  -> foo
```

```{r}
foo %>% 
  unlist(dp_links)
```

