---
output: github_document
---

<!-- README.md is generated from README.Rmd. Please edit that file -->

```{r, include = FALSE}
knitr::opts_chunk$set(
  collapse = TRUE,
  comment = "#>"
)
```

- applied data cleaning/wrangling ; iteration ; file handling
- day three tips, case study (iterate ingest read_csv ; clean / regex map() ; nested data frames ; write)
- functions


# workshop_rfun_iterate

<!-- badges: start -->
<!-- badges: end -->

## Raw Materials

iteration
data cleaning

refq_general/iteration_purrr
refq_general/dplyr_programming.Rmd

refq_
general/clean_data_applied.Rmd
refq_general/clean_data

### janitor::clean_names()

### with excel

~/refq_general/clean_data/01_trying_it_out.nb.html

### dplyr and the pain of dirty data  & case_when()

~/refq_general/clean_data_applied.nb.html

### funcitons / iteration purrr v for_loops / Regex

~/refq_general/iteration_purrr/purrr_map_outline.nb.html

### iterating with ggplot2 and models

~/r4ds/map_list_nest.nb.html

### time series and models (lubridate / clock)

~/r4ds/data_import_to_regression.nb.html

### include some tips 

https://oliviergimenez.github.io/tidyverse-tips/

### message HR data

~/r4ds/clean_data.nb.html
